import os
import csv
import shutil
import hashlib
from pathlib import Path
from collections import defaultdict, Counter

import pandas as pd
from PIL import Image
import imagehash
from tqdm import tqdm


# ============================================================
# CONFIGURATION
# ============================================================

DATASET = Path(r"W:\dataset\Final\_vehicledataset")

# Everything generated by this program goes here.
REPORT_DIR = DATASET / "CLEANING_REPORT"
QUARANTINE_DIR = DATASET / "QUARANTINE"

# Supported image formats
IMAGE_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".bmp",
    ".webp",
    ".tif",
    ".tiff"
}

# Images smaller than this are reported as suspicious.
MIN_WIDTH = 64
MIN_HEIGHT = 64

# If True, CLIP will be used to look for possible wrong labels.
USE_CLIP = True

# How much confidence difference is required before CLIP
# considers an image suspicious.
CLIP_SUSPICION_THRESHOLD = 0.15

# Do NOT automatically move images based on CLIP.
# False = report only.
# True = move suspicious images to quarantine.
AUTO_QUARANTINE_CLIP = False


# ============================================================
# CREATE DIRECTORIES
# ============================================================

REPORT_DIR.mkdir(exist_ok=True)
QUARANTINE_DIR.mkdir(exist_ok=True)

print("=" * 70)
print("VEHICLE DATASET CLEANER")
print("=" * 70)

print(f"\nDataset:")
print(DATASET)

if not DATASET.exists():
    print("\nERROR: Dataset path does not exist.")
    print("Check the drive letter and folder name.")
    input("\nPress Enter to exit...")
    raise SystemExit


# ============================================================
# FIND IMAGES
# ============================================================

print("\n[1/8] Scanning dataset...")

images = []

for path in DATASET.rglob("*"):

    # Don't scan our own generated folders
    if REPORT_DIR in path.parents or QUARANTINE_DIR in path.parents:
        continue

    if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS:
        images.append(path)

print(f"Images found: {len(images):,}")


# ============================================================
# DETERMINE LABELS
# ============================================================

print("\n[2/8] Detecting class labels...")

records = []

for path in images:

    relative = path.relative_to(DATASET)

    # First directory below dataset is assumed to be class
    parts = relative.parts

    if len(parts) >= 2:
        label = parts[0]
    else:
        label = "__NO_CLASS_FOLDER__"

    records.append({
        "path": str(path),
        "relative_path": str(relative),
        "label": label,
        "extension": path.suffix.lower(),
        "size_bytes": path.stat().st_size
    })


df = pd.DataFrame(records)

class_counts = Counter(df["label"])

print("\nClasses found:")

for label, count in sorted(class_counts.items()):
    print(f"  {label:<30} {count:,}")


# ============================================================
# CORRUPTED / INVALID IMAGES
# ============================================================

print("\n[3/8] Checking image integrity...")

corrupt_images = []
small_images = []
dimension_data = []

for path in tqdm(images, desc="Checking images"):

    try:

        with Image.open(path) as img:

            # Verify image internally
            img.verify()

        # Open again after verify
        with Image.open(path) as img:

            width, height = img.size

            dimension_data.append({
                "path": str(path),
                "width": width,
                "height": height,
                "format": img.format,
                "mode": img.mode
            })

            if width < MIN_WIDTH or height < MIN_HEIGHT:

                small_images.append({
                    "path": str(path),
                    "width": width,
                    "height": height
                })

    except Exception as e:

        corrupt_images.append({
            "path": str(path),
            "error": str(e)
        })


print(f"Corrupted/unreadable: {len(corrupt_images):,}")
print(f"Suspiciously small:     {len(small_images):,}")


# ============================================================
# EXACT DUPLICATE DETECTION
# ============================================================

print("\n[4/8] Searching for exact duplicate files...")

hash_groups = defaultdict(list)

for path in tqdm(images, desc="Hashing files"):

    try:

        sha256 = hashlib.sha256()

        with open(path, "rb") as f:

            while True:

                chunk = f.read(1024 * 1024)

                if not chunk:
                    break

                sha256.update(chunk)

        hash_groups[sha256.hexdigest()].append(path)

    except Exception:
        pass


duplicate_groups = []

for file_hash, paths in hash_groups.items():

    if len(paths) > 1:

        duplicate_groups.append({
            "hash": file_hash,
            "count": len(paths),
            "files": paths
        })


duplicate_rows = []

for group in duplicate_groups:

    for path in group["files"]:

        duplicate_rows.append({
            "hash": group["hash"],
            "duplicate_count": group["count"],
            "path": str(path)
        })


print(f"Duplicate groups: {len(duplicate_groups):,}")
print(
    f"Files involved in duplicates: "
    f"{len(duplicate_rows):,}"
)


# ============================================================
# CROSS-CLASS DUPLICATE DETECTION
# ============================================================

print("\n[5/8] Checking for images duplicated across different labels...")

cross_class_duplicates = []

for group in duplicate_groups:

    labels = set()

    for path in group["files"]:

        try:
            relative = path.relative_to(DATASET)
            parts = relative.parts

            if len(parts) >= 2:
                labels.add(parts[0])

        except Exception:
            pass

    if len(labels) > 1:

        for path in group["files"]:

            relative = path.relative_to(DATASET)

            label = (
                relative.parts[0]
                if len(relative.parts) >= 2
                else "__NO_CLASS_FOLDER__"
            )

            cross_class_duplicates.append({
                "hash": group["hash"],
                "label": label,
                "path": str(path)
            })


print(
    f"Cross-class duplicate files: "
    f"{len(cross_class_duplicates):,}"
)


# ============================================================
# PERCEPTUAL DUPLICATE DETECTION
# ============================================================

print("\n[6/8] Searching for visually similar images...")

print(
    "This can take some time on a large dataset."
)

phash_groups = defaultdict(list)

for path in tqdm(images, desc="Calculating perceptual hashes"):

    try:

        with Image.open(path) as img:

            img = img.convert("RGB")

            phash = str(imagehash.phash(img))

            phash_groups[phash].append(path)

    except Exception:
        pass


perceptual_duplicates = []

for phash, paths in phash_groups.items():

    if len(paths) > 1:

        labels = set()

        for path in paths:

            try:

                relative = path.relative_to(DATASET)

                if len(relative.parts) >= 2:
                    labels.add(relative.parts[0])

            except Exception:
                pass

        if len(labels) > 1:

            for path in paths:

                relative = path.relative_to(DATASET)

                label = (
                    relative.parts[0]
                    if len(relative.parts) >= 2
                    else "__NO_CLASS_FOLDER__"
                )

                perceptual_duplicates.append({
                    "phash": phash,
                    "label": label,
                    "path": str(path)
                })


print(
    f"Potential visually-similar cross-class images: "
    f"{len(perceptual_duplicates):,}"
)


# ============================================================
# CLASS IMBALANCE REPORT
# ============================================================

print("\n[7/8] Analysing class distribution...")

class_rows = []

for label, count in sorted(class_counts.items()):

    class_rows.append({
        "class": label,
        "image_count": count
    })


# ============================================================
# OPTIONAL CLIP LABEL VERIFICATION
# ============================================================

clip_results = []

if USE_CLIP:

    print("\n[8/8] AI-assisted label verification")
    print("-" * 70)

    try:

        import torch
        from transformers import CLIPProcessor, CLIPModel

        print("Loading CLIP model...")

        device = "cuda" if torch.cuda.is_available() else "cpu"

        print(f"Device: {device}")

        model_name = "openai/clip-vit-base-patch32"

        processor = CLIPProcessor.from_pretrained(model_name)

        model = CLIPModel.from_pretrained(model_name)

        model.to(device)

        model.eval()

        labels = sorted(
            label for label in class_counts
            if label != "__NO_CLASS_FOLDER__"
        )

        if len(labels) > 0:

            # Build natural-language descriptions.
            text_labels = [
                f"a photo of a {label.replace('_', ' ')}"
                for label in labels
            ]

            text_inputs = processor(
                text=text_labels,
                return_tensors="pt",
                padding=True
            )

            text_inputs = {
                k: v.to(device)
                for k, v in text_inputs.items()
            }

            with torch.no_grad():

                text_features = model.get_text_features(
                    **text_inputs
                )

                text_features = (
                    text_features /
                    text_features.norm(
                        dim=-1,
                        keepdim=True
                    )
                )

            print(
                f"Comparing images against "
                f"{len(labels)} classes..."
            )

            for path in tqdm(
                images,
                desc="AI label checking"
            ):

                try:

                    relative = path.relative_to(DATASET)

                    if len(relative.parts) < 2:
                        continue

                    actual_label = relative.parts[0]

                    with Image.open(path) as img:

                        image = img.convert("RGB")

                    inputs = processor(
                        images=image,
                        return_tensors="pt"
                    )

                    inputs = {
                        k: v.to(device)
                        for k, v in inputs.items()
                    }

                    with torch.no_grad():

                        image_features = model.get_image_features(
                            **inputs
                        )

                        image_features = (
                            image_features /
                            image_features.norm(
                                dim=-1,
                                keepdim=True
                            )
                        )

                        similarity = (
                            image_features @
                            text_features.T
                        )[0]

                        probabilities = similarity.softmax(
                            dim=0
                        )

                    best_index = int(
                        torch.argmax(probabilities)
                    )

                    predicted_label = labels[best_index]

                    predicted_confidence = float(
                        probabilities[best_index]
                    )

                    actual_index = labels.index(
                        actual_label
                    )

                    actual_confidence = float(
                        probabilities[actual_index]
                    )

                    suspicious = (
                        predicted_label != actual_label
                        and
                        (
                            predicted_confidence -
                            actual_confidence
                        ) >= CLIP_SUSPICION_THRESHOLD
                    )

                    clip_results.append({
                        "path": str(path),
                        "current_label": actual_label,
                        "predicted_label": predicted_label,
                        "predicted_confidence":
                            round(
                                predicted_confidence,
                                4
                            ),
                        "current_label_confidence":
                            round(
                                actual_confidence,
                                4
                            ),
                        "suspicious": suspicious
                    })

                except Exception as e:

                    clip_results.append({
                        "path": str(path),
                        "current_label": "",
                        "predicted_label": "",
                        "predicted_confidence": "",
                        "current_label_confidence": "",
                        "suspicious":
                            False,
                        "error": str(e)
                    })

            print(
                "\nAI label checking complete."
            )

        else:

            print(
                "No usable class folders found."
            )

    except ImportError:

        print(
            "\nCLIP dependencies are not installed."
        )

        print(
            "Run:"
        )

        print(
            "pip install torch torchvision transformers"
        )

        print(
            "\nContinuing without AI label verification..."
        )

    except Exception as e:

        print(
            "\nCould not run CLIP:"
        )

        print(e)

        print(
            "\nContinuing with normal dataset analysis..."
        )

else:

    print(
        "\nCLIP checking disabled in configuration."
    )


# ============================================================
# SAVE REPORTS
# ============================================================

print("\nSaving reports...")


# Class distribution
pd.DataFrame(
    class_rows
).to_csv(
    REPORT_DIR / "class_distribution.csv",
    index=False
)


# Corrupt images
pd.DataFrame(
    corrupt_images
).to_csv(
    REPORT_DIR / "corrupt_images.csv",
    index=False
)


# Small images
pd.DataFrame(
    small_images
).to_csv(
    REPORT_DIR / "small_images.csv",
    index=False
)


# Exact duplicates
pd.DataFrame(
    duplicate_rows
).to_csv(
    REPORT_DIR / "exact_duplicates.csv",
    index=False
)


# Cross-class duplicates
pd.DataFrame(
    cross_class_duplicates
).to_csv(
    REPORT_DIR / "cross_class_duplicates.csv",
    index=False
)


# Perceptual duplicates
pd.DataFrame(
    perceptual_duplicates
).to_csv(
    REPORT_DIR / "visual_cross_class_duplicates.csv",
    index=False
)


# Image dimensions
pd.DataFrame(
    dimension_data
).to_csv(
    REPORT_DIR / "image_dimensions.csv",
    index=False
)


# CLIP results
if clip_results:

    clip_df = pd.DataFrame(clip_results)

    clip_df.to_csv(
        REPORT_DIR / "ai_label_verification.csv",
        index=False
    )

    suspicious_clip = clip_df[
        clip_df["suspicious"] == True
    ]

    suspicious_clip.to_csv(
        REPORT_DIR /
        "SUSPICIOUS_LABELS_FOR_REVIEW.csv",
        index=False
    )


# ============================================================
# SUMMARY
# ============================================================

print("\n")
print("=" * 70)
print("DATASET AUDIT COMPLETE")
print("=" * 70)

print(f"\nTotal images:              {len(images):,}")
print(f"Classes:                   {len(class_counts):,}")
print(f"Corrupted images:          {len(corrupt_images):,}")
print(f"Small images:              {len(small_images):,}")
print(f"Duplicate groups:          {len(duplicate_groups):,}")
print(
    f"Cross-class duplicates:    "
    f"{len(cross_class_duplicates):,}"
)
print(
    f"Visual cross-class issues: "
    f"{len(perceptual_duplicates):,}"
)

if clip_results:

    suspicious_count = sum(
        1
        for x in clip_results
        if x.get("suspicious") is True
    )

    print(
        f"AI-suspicious labels:      "
        f"{suspicious_count:,}"
    )


print("\nReports saved to:")

print(REPORT_DIR)

print("\nIMPORTANT:")
print(
    "No original images were deleted or renamed."
)

print(
    "Review SUSPICIOUS_LABELS_FOR_REVIEW.csv "
    "before changing labels."
)

print("\nDone.")
input("\nPress Enter to exit...")
